server:
  port: 2021
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_test?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 980307
  quartz:
    job-store-type: jdbc
    jdbc:
      schema: classpath:schema/tables_mysql.sql
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:mapper/*.xml
logging:
  level:
    com.wujia.demo_event.mapper: debug